# This playbook prints a simple debug message
- name: Echo 
  hosts: 127.0.0.1
  connection: local

  tasks:
  - name: Print debug message
    debug:
      msg: New Message!
  - name: Lookup variable in Conjurdebug
    debug:
      msg: "{{ lookup('cyberark.conjur.conjur_variable', 'data/vault/Armin-conjur/Certificates-Certificates/password') }}"

