# This playbook prints a simple debug message
- name: Echo 
  hosts: localhost
  connection: local

  tasks:
  - name: Print debug message
    debug:
      msg: New Message!
  - name: Print Conjur Secret
    debug:
      "Username: {{ lookup('env', 'conjur_username') }}"

