# This playbook prints a simple debug message
- name: Echo 
  hosts: localhost
  connection: local

  tasks:
  - name: Print debug message
    debug:
      msg: New Message!
  - name: Show SSH username
    debug:
      msg: "SSH Username: {{ ansible_user }}"



